.github/workflows/fms-testing-app.yml

when using ghstack, this workflow wasn't running because the `on` filters by branch.
We'll still need to do https://github.com/foundation-model-stack/foundation-model-stack/issues/43 before we'd be able to use ghstack but this change removes one barrier.

remove branch filter because limits compatibility with ghstack

---

fms/models/llama.py
scripts/benchmark_inference.py
scripts/inference.py

creating the tokenizer and model from the same function is a bit awkward in some scripts that may be creating a llama instance from scratch or using this function

separate model and tokenizer creation

---

fms/distributed/tensorparallel.py
fms/models/llama.py
scripts/inference.py

This fixes `all_gather` dimensions not being correct, as after adding the transpose we forgot to change the dimension where we're gathering.
Two smaller fixes: this prevents a graph break during the `all_gather `autograd function by activating torch.no_grad() (see https://github.com/pytorch/pytorch/issues/107824 for more details), and adds the ability to pass kwargs to llama model init from the `load_fms_llama` function.

Fix all_gather dimension mismatch

---

fms/utils/config.py
tests/utils/test_config.py

When calling updated method on a ModelConfig with unknown parameters given, we would get a lot of prints, which was not intended. Now using logger debug for print statements when unknown params given to updated method in ModelConfig. This was occurring because the PretrainedConfig (HF) equivalent config had more params than what was in the ModelConfig and ModelConfig would just ignore them, however print a message. 
Note: We may want to consider also inspecting the dataclass to only pass those params that exist when converting from hf config to fms-hf config.

switched to logger for unknown parameters given to updated method in ModelConfig

---

fms/models/hf/llama/__init__.py
fms/models/hf/utils.py
fms/testing/_internal/hf/model_test_suite.py
tests/models/hf/test_llama_hf.py

- added AutoModel support for  HFAdaptedLLaMAHeadless
- added test suite for automodel/autoconfig in hf adapters model_test_suite
- fixed minor docstring param name in get_model for llama

AutoModel support for HFAdaptedLLaMAHeadless and AutoModel/AutoConfig test cases

---

fms/utils/tensors.py
tests/utils/test_tensors.py

adds an expandable tensor that uses preallocated space to avoid excessive copying on repeated torch.cat operations.
The hope is that this may be useful as an optimization for kv caching, by preallocating the kv cache space.
See: https://github.com/foundation-model-stack/foundation-model-stack/pull/84

add an expandable tensor

---

fms/utils/tensors.py
tests/utils/test_tensors.py

bugfix. torch.cat is still in-place, and so modifications to the original tensor will still be reflected, but the cat operation itself shouldn't result in the original `expandable` having a new `.size()`.

cat of expandable shouldn't change _dim_length in-place

---

fms/models/hf/llama/__init__.py

fixed issue where hf conversion to fms adapted hf model (get_model) does not carry over pad_token_id. This issue came about from errors when Huggingface generation is called on a batch where one of the sequences in the batch terminates early.

get_model for HF adapted llama conversion now carries pad_token_id over from hf model

---

fms/utils/tokenizers.py
tests/utils/test_tokenizers.py

Added bos/eos tokens and explicit "style" lookup.
we use tokenizers from multiple sources in testing, and the bos/eos are tied to the tokenizer, so easier to write scripts where the tokenizer has an explicit bos/eos attached to it.

minor improvements to the tokenizer api

---

.github/workflows/fms-testing-app.yml
fms/models/hf/gpt_bigcode/configuration_gpt_bigcode_hf.py

HFAdaptedGPTBigCode was defaulting tie_word_embeddings=False even though the value in the underlying model was tie_heads=True. When creating from an FMS model, this is not an issue as the heads have already been tied, however if we do `from_pretrained`, this is not known and must fall back to tie_word_embeddings. 
Note: It is a little surprising this did not run into issue in transformers version 4.34.1 and lower (need to investigate that further). Having said that, this seems like the right thing to be doing as tie_word_embeddings=True should be the correct value for this model

Fix tie heads bug in HFAdaptedGPTBigCode found in transformers 4.35.0

---

fms/distributed/__init__.py
fms/models/__init__.py
fms/models/llama.py
fms/utils/serialization.py
tests/models/test_models.py
tests/utils/test_serialization.py

As discussed internally, we want an API to load a model checkpoint based on a specified data source, data sharding format, and model distribution strategy in a general way, and where a variety of source formats can be added for any of the fms models.

An API for loading from a variety of available model checkpoints

---

fms/models/__init__.py
scripts/benchmark_inference.py

Make use of the 'get_model' API that fetches configurations of named models instead of relying on a file system path and full  load of all weights. This makes the benchmarking script run faster, we don't actually need to load the weights in order to benchmark.

save time in benchmarking script, doesn't need to load weights

---

fms/models/__init__.py

automatically trying to use MP when multiple GPUs are available is causing confusion, disabling.
https://github.com/foundation-model-stack/foundation-model-stack/issues/95

dont try to use mp automatically

---

fms/models/hf/llama/configuration_llama_hf.py
fms/models/llama.py

norm_eps in llama config was default to 1e-6, however it should have been 1e-5

fixed default value for norm_eps as it was incorrect

---

fms/models/hf/__init__.py
fms/models/hf/modeling_hf_adapter.py
fms/models/hf/utils.py
fms/testing/_internal/hf/model_test_suite.py
tests/models/hf_equivalence/test_llama.py

Currently, in order to get the HF adapted FMS model variant, one would need to know the model type and call the appropriate `model_class.from_fms_model` method. This was somewhat cumbersome and was not great for writing generic script writing as you would need to provide logic to decide what model to create. This PR introduces a new `wrap` method which will determine the type of FMS model and provide the proper wrapping.
before:
```python
model = get_model("llama", "7b", model_path=model_path, source="hf", device_type="cuda")
model = HFAdaptedLLaMAForCausalLM.from_fms_model(model)
```
after
```python
model = get_model("llama", "7b", model_path=model_path, source="hf", device_type="cuda")
model = wrap(model)
```

wrapper utility method for wrapping an FMS model with a Huggingface API

---

scripts/inference.py

This PR adds the usage of `get_model` to the inference script, as well as some args for it so more models can be used in the script. If ghstack was working, this would be the first of 3.

Small improvement to the example inference script

---

.github/workflows/ghstack_land.yaml
.github/workflows/slash.yml

* #148
* __->__ #147
Add an horray emoji as reaction to a slash command comment to imply
success. Add a comment with a link to the logs in case of failure.
Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

Add positive and negative feedback to slash commands

---

fms/modules/attention.py
fms/modules/embedding.py
fms/modules/feedforward.py
fms/modules/positions.py
fms/modules/tp.py
tests/distributed/test_tp.py

This cleans the implementation of TP to use a mixin class (TPModule). If ghstack was working, this would be 2/3, so inference.py can be ignored safely.

Cleaner TP

---

fms/modules/positions.py

* __->__ #130
Technically this should be more correct in cases where a key length and
value length differ. No change to existing behavior or current models
using it.

Separate key from value in rotary embeddings

---

.github/workflows/lint.yml
fms/models/gpt_bigcode.py
fms/models/hf/modeling_hf_adapter.py
tests/models/hf/test_llama_hf.py

* __->__ #158
Fix linter CI failures that popped up in CI.
Add the --diff --color options to the black lineter to
help fix linter failures in the future.
Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

Fix linter CI failures

---

.github/workflows/lint.yml

* __->__ #159
Pin the version of black, the python linter, to avoid pulling in
new versions that might break CI.
Use the compatibility operator =~ which means new non-breaking
patch versions are allowed, for instance 23.3.1 is allowed but
23.4.x or 24.x are not.
Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

Pin the version of black

---

.github/workflows/fms-testing-app.yml
.github/workflows/mypy.yml
hf-requirements.txt
requirements.txt
test-requirements.txt

* __->__ #174
The fms-testing and mypy CI job install FMS dependencies and test
dependencies for every CI job, which is time and resource consuming.
Start caching the python virtualenv using GitHub caches. Introduce
requirement files with pinned dependencies which are then used
as keys to distinguish cache hits or miss.
Rather than caching the pip cache, we cache the entire virtualenv
as that further saves the installation time.
Signed-off-by: Andrea Frittoli <andrea.frittoli@gmail.com>

Cache python dependencies in workflows

---

.github/workflows/scripts/ghstack-perm-check.py

The check for non-None pr_owner incorrectly re-tested actor which was previously confirmed to not be None.

Update ghstack-perm-check.py to fix non-None check

---

fms/modules/attention.py
fms/modules/positions.py
tests/modules/test_positions.py

Currently in Rope we assume the data comes in the format - `batch x num_heads x sequence_length x head_size` which requires us to transpose the input prior to going into Rope. In the current code, this won't really cause much issue as we end up transposing for SDPA as it has strict input requirements. In the future we may want to use other forms of attention (most not having that strict requirement), this will save us on doing extra contiguous/reshape calls. For instance, if we want to use this Rope implementation with Flash attention or Paged Attention, now we be in proper format which does not require doing extra transpose/reshape/contiguous calls

Contiguous Rope

---

fms/utils/tp_wrapping.py

Currently, if a user creates a custom module, there is no way to apply tensor-parallel to it given we only look for specific fms classes. This simple change enables a user to implement a `to_tp(group)` method which returns the TPModule version of the module. In the future, we may want to reconsider how TP is being done using something like DTensor, however in the short term, this will enable tp on custom modules.

added a to_tp check when applying tp so custom modules could enable tp

---

fms/models/gpt_bigcode.py

Fixes error `RuntimeError: Expected attn_mask dtype to be bool or to match query dtype, but got attn_mask.dtype: float and  query.dtype: c10::BFloat16 instead.` in the following stack trace, for a bfloat16 gpt_bigcode model variant:
```  
File "/lustre/suneja/foundation-model-stack/fms/utils/generation.py", line 75, in generate    
output = model(input_ids, **kwargs)
File "/lustre/suneja/foundation-model-stack/fms/models/gpt_bigcode.py", line 313, in forward
output, cache = self.base_model(    
File "/lustre/suneja/foundation-model-stack/fms/models/gpt_bigcode.py", line 236, in forward
output = layer(
File "/lustre/suneja/foundation-model-stack/fms/models/gpt_bigcode.py", line 81, in forward
x = self.attn(            
File "/lustre/suneja/foundation-model-stack/fms/modules/attention.py", …
```

Fix mask's dtype in gpt_bigcode

---

scripts/benchmark_inference.py

This PR makes results of `scripts/benchmark_inference.py` deterministic run by run.
The current implementation generates different results run by run. This behavior makes debugging hard when we add new features. This PR makes debugging easier.

Make benchmark results deterministic run-by-run

---

fms/models/llama.py

See https://github.com/foundation-model-stack/fms-fsdp/pull/65
Allows us to verify that FSDP-linked model initialization is working as intended in distributed pretraining contexts
Note that this is currently implemented solely for Llama. I can add this `validate_reset_parameters()` function to our other architectures as well if needed.

Add Llama initialization correctness check

---

scripts/inference.py

This is a follow-up PR of https://github.com/foundation-model-stack/foundation-model-stack/pull/221.
This PR makes consistent with `--deterministic` behavior by setting a specific random seed. This PR will make our debugging easier by generating the same result.

Make results deterministic in inference.py

---

scripts/benchmark_inference.py

This PR adds a guard to check whether cuda is available before calling cuda function. The runtime error occurs w/o this PR on non-CUDA environment (e.g. PyTorch cpu package).

Avoid runtime exception on non-CUDA environment

---

fms/models/gpt_bigcode.py
fms/utils/serialization.py

Now that we are using mmap for loading, we no longer need FusableWeightsMissingError. This also simplifies our model loading as we no longer need to run the adapter on a partial state dict.
- #244
- #243
- #248 
- -> #241

Remove FusableWeightsMissingError

---

fms/models/gpt_bigcode.py
fms/modules/tp.py

- fixed a bug where if copy rowwise is called with is_sharded=False, exception gets raised
- fixed a bug where a weight was not getting removed from the state dict prior to applying tp for gpt_bigcode

GPTBigCode Tensor-Parallel Bug Fix

---

fms/models/gpt_bigcode.py

- Added 3B variant to GPTBigCode
- updated adapter for hf to handle head_size=96 when emb_dim=3072 (currently it's hardcoded to 128) - we cannot recover the head_size from the weights here so we just opt to do a best guess for now

GPTBigCode 3B variant support

---

fms/modules/attention.py
fms/modules/positions.py

When creating the kv-cache, we can do it in two ways: either we store batch x sequence x heads x embedding (BSHE), or we store batch x heads x sequence x embedding (BHSE. Semantically, and that's why SDPA has that as their API, BHSE, is the one that makes the most sense, as batch and heads are both batching dimensions for the attention operation, while the ops are actually done on the seq x emb dimensions.
That being said, the outputs of the query, key, and value linear projections are in BSHE, and all modern SDPA algorithms (e.g. Flash, mem-efficient, Paged, etc.) want the inputs to be contiguous when in BSHE form, even if their APIs take the BHSE. For example, SDPA will immediately transpose back the inputs when calling Flash.
Therefore, it's more efficient and better compatibility for …

Swap kv-cache to be B x S x H x E for better compatibility and efficiency

---

fms/models/llama.py

LLaMA in Huggingface now accepted attn bias and mlp_bias. Adding that here as it is a simple configuration change. In this way, we can now support calico as a specific variant of llama

added attn bias, mlp bias, tie heads support to llama

---

fms/utils/generation.py
fms/utils/tokenizers.py
scripts/inference.py
tests/data/test_datasets.py
tests/utils/test_tokenizers.py

bug in handling of tokens vs list of tokens #103
before the previous fix to this issue, `eos_token_id` in generation.py was expected to be an integer. `eos_token_id` is the output of the function `convert_tokens_to_ids`. the previous fix made it so that this function would instead output a list, causing the existing code to error. 
so, eos_token_id is now a list, causing `torch.where(result == eos_token_id)` in generation.py to error.
Changes:
- since SP and HF tokenizers both originally returned integers when given a single str as input, the implementation for the char tokenizer was changed to make this uniform across all three tokenizers (i.e. now the char tokenizer returns an integer instead of a list of integers when given a single str input)
- restored sentencepiece tokenizer to its …

fixes to bug in handling single sentencepiece token

---

hf-requirements.txt

Numpy 2.0 was released on June 16th. PyTorch 2.2 is ready for Numpy 2.0 but the transformers library is not.
Pin numpy to <2.0 in the hf-requirements so that we use the correct version of numpy when using transformers.
Note: this is needed to unlock CI!

Pin numpy<2.0 for transformers

---

fms/utils/generation.py

This PR adds timing functionality to the generation utilities for both per-token and e2e. I have a question on how to expose this info back to the caller instead of printing directly in the function. Any suggestions @nairbv @JRosenkranz?

Add timing options for generation function

---

fms/models/hf/utils.py

fixed a bug where when loading an hf model to fms using as_fms_model, the kvheads config param was not being set properly

kvheads not set properly in as_fms_model when loading llama from hf

---

requirements.txt
scripts/eval_harness.py
test-requirements.txt

`scripts/eval_harness.py` does not work with the most recent version of lm_eval. the proposed change would make this script compatible with lm_eval == v0.4.2.
Fixes bug to reflect changes to lm-eval's general API. Call to `lm_eval.tasks.include_path()` is no longer needed according to v0.4.2: https://github.com/EleutherAI/lm-evaluation-harness/releases. 
This PR reflects this change in implementation and updates requirements.txt to use a more recent version of lm-eval.

update eval_harness.py to reflect updates to lm_eval package

---

fms/utils/generation.py

This PR adds a per-iteration hook to the generate() function.
One use-case for this function is adding debug information or running some kind of validation that requires more information about the status of the loop compared to what you get at the end of the generation loop.
For example, a use-case for this hook is to compare the logits being outputed by the model to some reference logits from another model implementation or the model running on another device.
The return values allow for the function to change the next token being added to the sequence or modify the kwargs being sent to the model for the next iteration.

Add post iteration hook to generation

---

fms/models/hf/llama/modeling_llama_hf.py

Currently, if a user wants to call `set_input_embeddings`, they do not have this option as it's not implemented for HFAdaptedLLaMADecoder. This PR adds that implementation.

set_input_embeddings implementation for HFAdaptedLLaMADecoder to enable resize_token_embeddings

---

fms/modules/attention.py
fms/modules/feedforward.py

This fixes the weight unfusing code now that we don't set default dtypes anymore inside get_model. It will grab the dtype from the weight it's unfusing instead of the default pytorch dtype.

Fix default dtype for unfuse weights

---

fms/modules/attention.py
fms/utils/generation.py
tests/utils/test_generate.py

Currently SDPA favors an additive mask. In this PR, we remove the boolean mask in favor of an additive mask

Fixed inefficiency in SDPA when using padding_kwargs

---

fms/models/__init__.py

This PR adds the option for `hf_pretrained` to take either a `variant` or a `model_path` to infer the configuration and load the weights of a model. This covers the case of HF checkpoints of models not yet available in the Hub, which neither of `hf_pretrained` or `hf_configured` were covering before.
cc @tdoublep

Improve `hf_pretrained` API for local HF models

---

fms/models/__init__.py
fms/models/gpt_bigcode.py
fms/models/llama.py
fms/utils/generation.py

This PR adds the missing `only_last_token` to GPTBigCode models to match Llama and Mixtral APIs.

Add only_last_token to GPTBigCode model to match other APIs

---

fms/models/__init__.py
fms/models/llama.py

- fix gptq adapter for llama models to properly transposes bias (needed for granite-8b)
- changed how a model is identified as "gptq", to include future "gptq_cpu" linear type
- gave more flexibility to gptq source, so that it can be passed as either "gptq_hf_unfused" (which selects the correct adapter) or "hf" (and automatically converted to "gptq_hf_unfused", for gptq models only)

Fix GPTQ llama adapter for granite-8b

---

fms/utils/generation.py

This PR forces the sequence dimension in the kv cache to be dynamic for torch.compile() if dynamic shapes are enabled for generate(). This reduces tracing time as one less trace needs to happen during generation. If the user forces static shapes when calling generate(), this is disabled.

Force dynamic shapes for kv cache in generate()

---

fms/models/hf/utils.py

wrapped `model_id_or_path` in str to fix mypy issue with transformers

Fixed mypy failure in CI

---

fms/testing/_internal/model_test_suite.py

Added this in the case of clashing names for an expectation test. This PR gives the user the ability to set a model name to make the expectation file path more specific.

Added option to specify model name in the model consistency test suite expectation file path

---

fms/models/hf/utils.py
fms/testing/comparison.py
fms/utils/generation.py

- Roberta for question-answering can now be inferred
- pad_input_ids no longer assumes a causal mask (is_causal_mask bool)
- comparison function for signatures now also takes the rtol param (defaulted to same as np.allclose)
- removed the backward call in `get_signature` as it is no longer required

Fixed issues inferring Roberta QA as well as added features for encoder-only testing

---

fms/utils/generation.py

This PR fixes generation code with torch.compile() and dynamic shapes when masks are in play. Before, we would get 3 compiled graphs due to the mask not being detected as dynamic early enough. Now, the issue is gone. Also, it covers an edge case where the kv cache is a list and not a tuple.

Add fixes for full dynamic with masks

---

fms/models/granite.py
fms/modules/linear.py

This PR adds support for INT8 (W8A8) Granite-3.X models generated with `fms-model-optimizer`.
In particular, Granite architecture also necessitates the HF-to-FMS RoPE transpose of K,V weights _and corresponding INT8 quantization parameters_ (like in GPTQ).
Additional details:
1. Weight quantization "per-channel" will generate a `quantize_weight.clip_val` in the input state dictionary, which is used to apply quantization along the out_feat weight dimension (1 clip per output feature). As this dimension is transposed, this `clip_val` needs to be transposed accordingly.
2. Weight quantization "per-tensor" will generate a single clip that applies to the full tensor. Transpose should not be applied to this parameter (hence the check `param.numel() > 1`).
3. Smoothquant applies scaling along …

Add support for fms_mo-based INT8 Granite

---

fms/utils/generation.py

added a `prepare_model_inputs_hook` which can be used to modify model inputs in the case a model either does not have fms apis, or some special setup is required.

Flexible model inputs in generate

---

fms/utils/generation.py

This avoids a 3rd graph generation during `generate()` with dynamic shapes, now for real

Fix extra graph generation during generate with contiguous cache

---

fms/testing/_internal/model_test_suite.py

This PR adds the option to include more params to model consistency testing to be passed to get_signature. This can be used to support params such as mask/position_ids.

added optional_params/input_ids option to consistency expectation testing

---

fms/models/roberta.py
tests/models/hf_equivalence/test_roberta.py

This PR adds a `token_type_embeddings` layer to RoBERTa in order to match the HF architecture for BERT / RoBERTa.
In some downstream tasks, `token_type_ids` are used to identify different sentences within a single input sequence, and processed via a `token_type_embeddings` layer.
While in some scenarios (such as in pre-trained RoBERTa) the token type embedding weights are zero, this is not always the case. For example, a fine-tuned model may have small, non-zero token_type_ids embedding weights even if the task does not strictly require them.
Adding a `token_type_embeddings` layer also fixes the warning for missed key when loading an HF/FMS-MO trained checkpoint into FMS/FMS-MO architecture:
```[WARNING] Keys from checkpoint (adapted to FMS) not copied into model: …
```

Add handling of token_type_ids to RoBERTa

---

fms/utils/serialization.py

During the loading of parameters from a checkpoint into a newly instantiated FMS architecture, the current behavior is "semi-silent": processing of other parameters will continue, the keyword corresponding to the parameter that failed is recorded in `unused_keys`, and the full list of unused keys is listed as warning printed out at the end of the checkpoint copy.
This behavior is undesirable for quantized models, where mismatch due to using a different quantization configurations between the trained checkpoint and the FMS architecture can go unnoticed. In this scenario, it is preferable to stop the checkpoint copy and raise an error.
As mismatched quantization configurations should result in a shape/size error during the copy (for example, when a per-channel quantization parameter from …

Raise exception in case of shape mismatch during ckpt loading

---

fms/models/hf/modeling_hf_adapter.py

Fix for the following:
```
HFDecoderModelArchitecture has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
```
```
>>> transformers.__version__
'4.52.0.dev0'
```
```
AttributeError: 'HFAdaptedLLaMAForCausalLM' object has no attribute 'generate'
```

[hf_adapter] added GenerationMixin for transformers version compatibility

---

fms/testing/comparison.py

With the latest attn_kwargs change, we no longer need to remove parameters to pass from option_params passed to get_signature as attn_kwargs will catch these

fix get_signature so that it no longer ignores some optional params

---

fms/utils/generation.py

In the very odd case where you only generate one token, that token is EOS, and also want per-token timings, the code would crash. This PR fixes this crash.

Delay the eos-based loop break to at least get one timing in

---

fms/models/hf/utils.py

Fixes the warning for many layer names that are not mapped into real modules names.
The issue is this warning that appears within every mistral inference:
```bash
[WARNING] Keys from checkpoint (adapted to FMS) not copied into model: {'layers.4.feed_forward.w3.weight', 'layers.29.ffn_norm.weight', 'layers.3.attention.wv.weight', 'layers.13.feed_forward.w2.weight', 'layers.0.ffn_norm.weight', 'layers.3.attention.wq.weight', 'layers.14.attention.wo.weight', 'layers.19.attention.wv.weight', 'layers.9.feed_forward.w1.weight', 'layers.26.feed_forward.w2.weight', 'layers.7.ffn_norm.weight', 'layers.31.attention.wq.weight', 'layers.8.feed_forward.w3.weight', 'layers.22.ffn_norm.weight', 'layers.8.ffn_norm.weight', 'layers.30.attention.wq.weight', 'layers.21.feed_forward.w3.weight', …
```

Verification for unused layers to remove warnings

---

fms/models/bamba.py
fms/models/gpt_bigcode.py
fms/models/granite.py
fms/models/hf/llama/modeling_llama_hf.py
fms/models/hf/mixtral/modeling_mixtral_hf.py
fms/models/llama.py
fms/models/mistral.py
fms/models/mixtral.py
fms/modules/attention.py

Unpack and NotRequired don't exist prior to python 3.11, this allows for compatibility.

[typing_extensions] for backwards compatibility
