fms/utils/__init__.py

fix bug in print0

---

README.md

updated the readme with install from pypi

added install from pypi to readme

---

README.md

@ani300 Can you update this README toward the end with the links to issues in flight? Specifically, group them into:
* Tensor parallel
* CUDA graphs

Redoing README

---

notebooks/hf_llama_generation_example.ipynb

Simple fix to add fp16 and cuda to hf sample notebook

added fp16 and cuda to hf sample notebook

---

fms/models/hf/README.md

Fixed typo in hf adapter readme

docs: fixed minor typo in hf adapter readme

---

fms/models/hf/gpt_bigcode/modeling_gpt_bigcode_hf.py

Removed this piece of code as it was already being done by the underlying base adapter.

remove override _prepare_inputs_for_generation in modeling_gpt_bigcode_hf

---

fms/models/llama.py
tests/models/hf_equivalence/test_llama.py

Added an implementation of LLaMA HF->FMS conversion adapter and registered it with the conversion adapters

LLaMA HF->FMS load_model conversion adapter

---

fms/datasets/__init__.py
fms/datasets/instructions.py
fms/datasets/text.py
tests/data/test_datasets.py

This is intended for use in the tuning script, to get a fine tuning dataset to use. Also fixed some bugs, e.g. an off-by-one error that came up in testing.

Add a dataset-fetching API

---

.github/workflows/lint.yml
.github/workflows/mypy.yml
fms/datasets/__init__.py
fms/datasets/instructions.py
fms/datasets/text.py
fms/distributed/strategy.py
fms/distributed/tensorparallel.py
fms/models/__init__.py
fms/models/gpt_bigcode.py
fms/models/hf/gpt_bigcode/__init__.py
fms/models/hf/gpt_bigcode/modeling_gpt_bigcode_hf.py
fms/models/hf/llama/modeling_llama_hf.py
fms/models/hf/modeling_hf_adapter.py
fms/models/llama.py
fms/modules/attention.py
fms/modules/embedding.py
fms/modules/feedforward.py
fms/modules/positions.py
fms/testing/_internal/model_test_suite.py
fms/training/plugins.py
fms/training/trainer.py
fms/utils/__init__.py
fms/utils/config.py
fms/utils/generation.py
fms/utils/serialization.py
fms/utils/tokenizers.py
tests/utils/test_generate.py

Adding mypy support in fms. Skipped the /hf/ path because transformers doesn't seem to have mypy stubs, and skipped testing, and have a lot of #ignore's in tensorparallel, but this gives us enforcement of type checking for most of our code.

add mypy type checking to most paths

---

scripts/train_causal.py

grad_accum_steps was defaulting to 10. changed to 1 and made it a command line option, also re-arranged the options.

change some defaults and rearrange params

---

fms/utils/generation.py

just a minor refactoring, separating out the part of `generate` related to `reduce-overhead`

minor refactoring of generate function

---

fms/datasets/__init__.py
tests/data/test_datasets.py

restartable datasets

---

fms/datasets/__init__.py
tests/data/test_datasets.py

re-apply https://github.com/foundation-model-stack/foundation-model-stack/pull/126 because the land command didn't work properly last time.

reapply restartable datasets from #126

---

.github/workflows/fms-testing-app.yml
.github/workflows/mypy.yml
fms/datasets/arrow.py
tests/data/test_arrow.py

replaces: https://github.com/foundation-model-stack/foundation-model-stack/pull/127

add a dataset that loads arrow files

---

fms/datasets/__init__.py
fms/datasets/arrow.py
tests/data/test_datasets.py

re-applies the pr from https://github.com/foundation-model-stack/foundation-model-stack/pull/128
this got a bit scrambled in trying to merge changes over from a ghstack branch

Adding a dataset to pack sequences

---

fms/distributed/strategy.py

fix a bug in size of layer_to_device

---

setup.py

Updated version to 0.0.3 release in preparation for new version distribution.
This version will include:
- safetensor weight loading support with model config
- improved tensor parallel api
- restartable datasets support
- arrow file dataset support
- packed sequence dataset support
- added a compostable dataset to add separators
- fixes to HF-Adapted LLaMA in multi-gpu environment
- fixed bugs in UniformModelParallel where layer_to_device size was incorrect
- isort checks for CI
- updates to inference script
- github support improvements (ghstack)
- separated the key from value in rotary embeddings

Version 0.0.3 release

---

fms/utils/serialization.py

Fix bug on adapters with fusable weights

---

README.md

suggestions to Readme

---

fms/models/gpt_bigcode.py

Noticed an unnecessary print in gpt_bigcode adapter, so removing in this PR

removed unnecessary print in gpt_bigcode

---

fms/training/plugins.py
scripts/train_causal.py

* #208
* __->__ #207
fixes: https://github.com/foundation-model-stack/foundation-model-stack/issues/114

accumulate training stats with correct ranks

---

fms/datasets/__init__.py

add a mock dataset for testing of training

---

fms/modules/attention.py

* #206
* #205
* #204
* #203
* #210
* #209
* __->__ #201
* #200

Small fix for GQA models on TP

---

fms/utils/__init__.py

correct ordering so hsdp only prints on one rank

---

fms/datasets/__init__.py
fms/datasets/arrow.py
fms/datasets/instructions.py
fms/datasets/text.py
fms/training/trainer.py
scripts/train_causal.py

reduce device/host transfers during training and batch inputs

---

fms/training/plugins.py

* #214
* __->__ #213
* #212
A bug was introduced by
https://github.com/foundation-model-stack/foundation-model-stack/pull/207
Since we report every `seconds` seconds, but now introduce a
dist.barrier via all_reduce, in any case where the current time doesn't
exactly match across hosts there can be a deadlock. Using average
seconds per step (and aggregating the average across hosts) fixes this.

Fix a race condition

---

fms/models/__init__.py
fms/models/gpt_bigcode.py
fms/models/hf/gpt_bigcode/__init__.py
fms/models/hf/gpt_bigcode/configuration_gpt_bigcode_hf.py
tests/models/test_gpt_bigcode.py

Add gpt big code to the FMS model register

---

fms/models/__init__.py
fms/training/plugins.py
fms/training/trainer.py
fms/utils/serialization.py
scripts/train_causal.py

add support for dataset and hsdp checkpointing during training

---

setup.py

Updated version to 0.0.4 release in preparation for new version distribution.

Version 0.0.4 release

---

fms/training/plugins.py
fms/training/trainer.py
scripts/train_causal.py

track elapsed tokens during training

---

setup.py

Updated version to 0.0.5 release in preparation for new version distribution.

Version 0.0.5 release

---

setup.py

Updated version to 0.0.6 release in preparation for new version distribution.
https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v0.0.6

updated version to 0.0.6

---

fms/__init__.py

fixes: https://github.com/foundation-model-stack/foundation-model-stack/issues/305

add __version__ to fms

---

fms/models/llama.py

This PR adds support for the configurations of all the open-sourced Granite models.
* __->__ #307

Add granite model support for Llama

---

fms/distributed/tensorparallel.py
fms/models/__init__.py
fms/modules/attention.py
fms/modules/embedding.py
fms/modules/feedforward.py

Arising from multinode speculator training.
Replaces #329 
@JRosenkranz
@ani300

TP: world_size percolation updates

---

fms/models/llama.py

When models tie weights, TP will break due to mismatched dimensions being sharded. This PR prevents that from happening.
cc @andrea-fasoli

Prevent TP from applying when tied_weights=True for Llama models

---

setup.py

https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v0.0.7

updated version to 0.0.7

---

fms/modules/attention.py

This short PR fixes TP for Granite 3.0 models by adding a missing parameter

Fix Granite 3.0 TP

---

setup.py

Release Notes: https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v0.0.8

updated version to 0.0.8

---

tests/models/test_models.py

Switched out current hf_pretrained test model with a smaller model to speed up test case

Fix issue where CICD fails occasionally on a test case

---

fms/models/hf/utils.py
fms/utils/serialization.py

Also add add `initial_device` to `torch.load` call for PT checkpoints to avoid missing GPU errors.

Change HF default checkpoint from bin to safetensors

---

fms/models/granite.py

This PR adds the steps required for Granite GPTQ weight adaptation from HF

Support for Granite GPTQ model weight adaptation from HF

---

fms/training/plugins.py

needed a quick training script to test something locally so used this one, but encountered a bug

fix some bugs in local/test training

---

fms/utils/generation.py

Fixes performance drop on some internal benchmarks

Fix performance when use_contiguous_cache=True

---

setup.py

Release Notes: https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v1.0.0

updated version to 1.0.0

---

setup.py

Release Notes: https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v1.1.0

updated version to 1.1.0

---

setup.py

Release Notes: https://github.com/foundation-model-stack/foundation-model-stack/releases/tag/v1.2.0

updated version to 1.2.0
